### ISSUE TITLE
[ Bug ] mouseDragged event handler

### ISSUE THREAD

**Issue by zndrmn** [Siphalor/mouse-wheelie#168]
**Version**
The Minecraft version and the version of this mod.

mousewheelie-1.8.8+mc1.18.2.jar
mc1.18.2

**Describe the bug**

I wasn't really paying any attention to what I was doing bc I was sorting things but here's the crashy link it gave me
[https://crashy.net/fvI86OPtQXzS9KnhgvMO](https://crashy.net/fvI86OPtQXzS9KnhgvMO)

**To Reproduce**
1. I was moving items from my inventory to a barrel and go kicked from my server
2. It crashed, I don't know what could've caused it

**Log**
The important parts of the log.

[https://crashy.net/fvI86OPtQXzS9KnhgvMO](https://crashy.net/fvI86OPtQXzS9KnhgvMO)
[https://gist.github.com/zndrmn/file-latest-log](https://gist.github.com/zndrmn/561676f32e55c533ca216deb5aa1d980#file-latest-log)
[https://gist.github.com/zndrmn/file-crash-2022-06-09_17-14-00-client-txt](https://gist.github.com/zndrmn/859f8eb74678ca8d4ba17a2979db93c6#file-crash-2022-06-09_17-14-00-client-txt)

**Comment by Siphalor** [comment]
I think, that that's another effect from the race condition I fixed in 268a2fef875141fae84e9e655fc27ab317a641fe.

Thanks for reporting this, I'll close this bug when the fix is out in the next release.

Since that race condition has a pretty slim chance of occuring, I don't think it will have a big impact until then :)

**Comment by zndrmn** [comment]
as a note, This has happened a few times before I reported it.

**Comment by Siphalor** [comment]
Fixed in 1.9.0 :)
