### ISSUE TITLE
Game crash with ArrayIndexOutOfBoundsException after sorting inventory[bug][can't reproduce]

### ISSUE THREAD

**Issue by Hanqnero** [Siphalor/mouse-wheelie#171]
**Minecraft Verison** 
1.18.2

**Bug**
Game crash with ArrayIndexOutOfBoundsException.

**То reproduce**
1. Sort inventory with these items and shulker box GUI open (not sure that second part is neccessary). After two crashes bug disappeared, never encountered it before.
2. Bug appears

**Log**
[crash-2022-06-17_19.23.42-client.txt](https://github.com/Siphalor/mouse-wheelie/files/8928534/crash-2022-06-17_19.23.42-client.txt)

**Additional context**
Inventory content that caused crash:
![image](https://user-images.githubusercontent.com/57258124/174320769-0d6773c3-7039-4bb8-b5e5-a642aa039997.png)

**Comment by Trnrr** [comment]
I also get this error. It's only happened to me when I have another inventory open (chest, shulker, machine GUI, etc).

Quilt: 0.17.0
mousewheelie-1.9.1+mc1.18.2

**Comment by PixelDew121** [comment]
Crashed when sorting a chest, specifically when hovering over Asurine blocks from create and using middle click to sort. Attempting to sort those blocks at a later time when the items were organized differently didn't cause issues. Unsure what specific layout of items led to the crash.

log - https://mclo.gs/huC5QL9

MC 1.18.2
MouseWheelie 1.9.1+mc1.18.2

**Comment by ripkordt** [comment]
Crashed when sorting inventory

log https://crashy.net/jgteTVZQIde6Y1z9FXF0

**Comment by Siphalor** [comment]
The reason of the bug is pretty boring: I just messed up some code during the last update.

I just want to lay out the exact cause of the crashes here, because it's pretty obscure:

When moving stacks around, and you want to move a stack with a lower count to a slot with a higher count, then you won't be able to swap them by just clicking on them.
My code actually has a workaround for that scenario and that's by picking another temporary slot that will be used to fiddle the smaller stack into place.
The issue was that that temporary slot was handled incorrectly after the update :)

This bug could only be potentially experienced when there's a lower stack count at the wrong position.
And even then it would depend on how some sorting internals would actually behave to cause the bug.

So over all a pretty simple fix for an extremely obscure bug ^^

Thanks everyone for submitting your details :heart:
