### ISSUE TITLE
[bug]  Crash 1.18.2 with tweed

### ISSUE THREAD

**Issue by Monster-Zer0** [Siphalor/mouse-wheelie#196]
**Version**
1.18.2
**Describe the bug**
crash on boot

https://aofpaste.com/ijaniwoput.yaml

**Comment by TheWyzer** [comment]
I also have the same issue since Mouse Wheelie version 1.10.3, and it also happens on current version 1.10.5
Fabric API 0.67.0
Fabric Loader 0.14.11
Minecraft 1.18.2
ModMenu 3.2.5
[crash-2022-12-17_23.36.03-client.txt](https://github.com/Siphalor/mouse-wheelie/files/10259944/crash-2022-12-17_23.36.03-client.txt)
