### ISSUE TITLE
[bug] Complete Config Incompatibility

### ISSUE THREAD

**Issue by zax71** [Siphalor/mouse-wheelie#198]
**Version**
1.19.3, 1.10.6
**Describe the bug**
Upon opening the Mod Menu from Mod Menu, there is a stack trace output to console and no config button in Mod Menu

**To Reproduce**
1. Install: CompleteConfig, Fabric API, Mod Menu and Mouse Wheelie on Fabric 1.19.3
2. Launch the game and click on "Mods" (Notice delay)
3. Navigate to Mouse Wheelie, notice no config button
4. Open logs, notice the stack trace

**Expected behaviour**
I expect there to be a config button in Mod Menu and no stack trace in the logs

**Log**
[Full log](https://mclo.gs/zTjZyfd)
[Stack trace in question](https://mclo.gs/uqsYDXG)
**Additional context**
Doesn't occur on 1.19.2

**Comment by Siphalor** [comment]
Thanks for the bug report.

That issue is caused by CompleteConfig using a version of Coat meat for an older Minecraft version - there's nothing I‌ can really do about it, so I opened an issue over there.

Temporarily you can either remove CompleteConfig or try to fix it manually by opening its jar and removing the `coat` related object in the `jars` section.

While this issue isn't actually related to Mouse Wheelie, I'm gonna keep this open for reference.

**Comment by zax71** [comment]
Thanks for getting back to me so quickly! I'll wait for CompleteConfig to update :)

**Comment by Lortseam** [comment]
@zax71 This is now fixed in CompleteConfig version 2.2.1.

**Comment by zax71** [comment]
Thanks for updating me!
