### ISSUE TITLE
[bug] Mod 1.19-1.19.2 will crash if you drop something on the server in large numbers with ctrl+alt+left click it's too annoying

### ISSUE THREAD

**Issue by m1ddl0ngg** [Siphalor/mouse-wheelie#200]
**Version**
The Minecraft version and the version of this mod.
**Describe the bug**

**To Reproduce**
1. Use this json or craft something.
2. Bug appears

**Expected behavior**

**Log**
The important parts of the log.

**Additional context**

**Comment by Siphalor** [comment]
Hi,
please provide the crash log (as indicated in the issue template).
Without a crash log I can do nothing about this.

**Comment by BlackKnight89K** [comment]
Hi Siphalor,
i have the same issue with the 1.19.1 and the 1.19.3 version.

My client crashes sometimes when:

- I drop a large amount (double ches full) at once with ctrl+alt+left click
- I masscraft for example ingots into blocks by holding ctrl+q over a item in the recipe book.

[crash-2023-01-19_09.57.16-client.txt](https://github.com/Siphalor/mouse-wheelie/files/10455149/crash-2023-01-19_09.57.16-client.txt)

I run my own server in a local network. But the issue also occures rarely in sp worlds. In a sp world, it seemed to help when i disable carpet mod. But that is not the case with the local server setup. Unfortunately the crash report doesn't contain class or method names. My client (the server is fine) crashes consistently with an IllegalStateException. Maby it's a multithread issue.

**Comment by Malsententia** [comment]
I have also encountered this problem, and I believe I have a log which specifically points to mouse-wheelie. it seems that when the crash actually happens, it's from some something else failing in a thread related issue caused by mouse-wheelie. Something about how a randomness source is being accessed by multiple threads. I get an error every time I drop the entire contents of a chest(this is visible in the logs), but sometimes, that action seems to conflict with other code in the game, causing the crash(logs at that point do not include mousewheelie), but I think that's because mouse-wheelie is competing for the randomness source or st, and code elsewhere fails as a result? I'm not familiar with the code, but I hope this helps in some way.
[output.log](https://github.com/Siphalor/mouse-wheelie/files/10504110/output.log)
