### ISSUE TITLE
[bug] All Modrinth versions have the same changelog 

### ISSUE THREAD

**Issue by zax71** [Siphalor/mouse-wheelie#221]
**Version**
Mod version 1.10.7+
**Describe the bug**
All Modrinth versions past 1.10.7 have the same changelog 

**To Reproduce**
1. Open the Modrinth page for mouse wheelie
2. Go to the versions tab
3. Observe changelog on a version past 1.10.7
4. Observe a different version
5. Same changelog 

**Expected behaviour**
Change logs to reflect actual changes.

**Comment by Siphalor** [comment]
There are no versions past 1.10.7 :wink: (yet)

Mouse Wheelie supports all major versions starting with Minecraft 1.14.4 and each release (e.g. 1.10.7) will be published for each of these Minecraft versions.
Since the Minecraft versions all receive the same changes (unless otherwise noted), they all have the same change log.
