### ISSUE TITLE
[bug] My sword took penalty for me trusting MW with tool choice for oak leaves.

### ISSUE THREAD

**Issue by mk-pmb** [Siphalor/mouse-wheelie#222]
**Version**
Minecraft 1.19.4, mousewheelie-1.10.7+mc1.19.4.jar
**Describe the bug**
I wanted to use MW to learn wich tool would be correct. Minecraft punished my bad choice of tool.

**To Reproduce**
1. I enabled select correct tool when middle-clicking with any tool.
2. I middle-clicked oak leaves with my axe.
3. MW selected my stone sword.
4. I cut one block of oak leaves.
5. My sword took extra durability penalty (2 points deducted).

**Expected behavior**
MW chooses a tool that Minecraft accepts without penalty. (MC Wiki says shears or hoe. I'm undecided which MW should prefer.)

**Log**

**Additional context**
If MW uses another definition of "correct" tool, we should instead clarify the config options.

**Comment by mk-pmb** [comment]
Now that I know which tools would have been accepted, I realize I had none of them with me. We need some kind of error notification for this. Maybe not changing the slot, and instead highlighting the slot with a reddish tint for 2–5 seconds, or until I interact with that slot or select another slot.

**Comment by Siphalor** [comment]
That's actually working as intended, although I was surprised to see that in the Minecraft Wiki myself ^^

![image](https://github.com/Siphalor/mouse-wheelie/assets/24505659/f1b54750-0bd0-4a59-934b-1b5f1ab2aec3)

Swords are an effective tool for leaves, even though they take more damage from it.
Since Mouse Wheelie checks for the tools that are effective and quickest to mine the block, and you probably didn't carry a hoe or shears, the sword is the most effective tool for leaves in your inventory.
