### ISSUE TITLE
Doesn't work well with another mod [bug] 

### ISSUE THREAD

**Issue by KIRUYXAN** [Siphalor/mouse-wheelie#238]
**Version**
Fabric 1.19.2; Mod 1.12.0

**Describe the bug**
The Traveler's Backpack mod has tool slots that allow you to quickly swap out a tool in hand for a tool in the slot, but the new feature (which is "e.g. emptying or filling water buckets will now refill the buckets.") in this mod changes my diamond pickaxe , when shifting it from the hand to the slot, on the one that lies in the inventory.

**Expected behavior**
Please make the new feature either not react to the tools at all, or so that it can be customized to what it will react to.

**Comment by Siphalor** [comment]
Hi, thanks for the suggestion.

Out of interest, does turning off "Refill on other occasions" in the Refill settings fix your issue?

Since I don't really like hardcoding stuff or letting the player specify allow/deny lists through weird menus, I'm thinking about a third option:

As you might guess from the title and the description (exactly the same xD) of that config option, it's a bit of a wildcard where I'm not even sure for which cases this is exactly necessary.  
Under the assumption, that that option fixes your issue, I might turn it off by default and allow the player to refill items "on demand" using a key binding.

Nothing is set in stone yet, I'm still debating on what's the most intuitive behavior for this.

**Comment by KIRUYXAN** [comment]
Turning off "Refill on other occasions" helped, thanks
