### ISSUE TITLE
[bug] Servers Sorting

### ISSUE THREAD

**Issue by Joly0** [Siphalor/mouse-wheelie#38]
**Version**
1.2.12+1.14.4
**Describe the bug**
If i try to sort my chests, it doesnt really work. It looks like, my game randomly picks up items and places them somewhere in the chest. I didnt tested this in Singleplayer, only on a Server.

**To Reproduce**
1. Join Server
2. Open chest
3. Press middle click
4. Bug appears

**Expected behavior**
The chest should get sorted

**Comment by Siphalor** [comment]
I lately played and sorted a lot on servers (version 1.2.13+1.14.4) and some of my friends too. Neither of us experienced those bugs.
Until there I can reproduce this myself or someone can give me a good clue why this happens I'll unfortunately have to mark this as "can't reproduce".

**Comment by Siphalor** [comment]
Is this still a problem?

**Comment by xAlicatt** [comment]
I'm not able to sort since updating to MW 1.3.8 with Fabric API 0.4.1build 245 and Fabric Loader 0.7.2 build 174 on a multiplayer server when I was previously able to using MW 1.3.1

Edit: Turns out the key control got reset somehow when I updated? In any case, I fixed that and it's working fine now. The server does not have the mod installed.

**Comment by Siphalor** [comment]
I just hope that this thing is gone now.

btw since a few months i've been working on a new sorting kind of engine. Coming soon©®™️
